# Generated by scripts/update-homebrew-tap.js — edit the script, not this file.
cask "jolo" do
  version "0.2.4"

  arch arm: "arm64", intel: "x64"

  sha256 arm:   "951b8fd6cc96485dd4ad8c72d43b4b2826766c63426407f1d8ffaddacb7464bb",
         intel: "a81fa776c239137fd359e8699dcd3dba98eba254afa2da527073cdc30e1c6c7a"

  url "https://github.com/jolo-build/jolo/releases/download/v#{version}/jolo-desktop-darwin-#{arch}.dmg"
  name "Jolo"
  desc "Desktop app for working with coding agents"
  homepage "https://jolo.build"

  app "Jolo.app"

  zap trash: [
    "~/Library/Application Support/Jolo",
    "~/Library/Caches/jolo",
    "~/Library/Preferences/dev.jolo.desktop.plist",
    "~/Library/Saved Application State/dev.jolo.desktop.savedState",
  ]
end
