# Generated by scripts/update-homebrew-tap.js — edit the script, not this file.
cask "jolo" do
  version "0.2.6"

  arch arm: "arm64", intel: "x64"

  sha256 arm:   "997f12ea437a03fe34f02136db16e6f1e79ca69fc8d1768683f0e7c54fb86297",
         intel: "f13812f676790ed418b4701c4a800109faaa6d9c73523471c8a7e7f9bba4a3d5"

  url "https://github.com/jolo-build/jolo/releases/download/v#{version}/jolo-desktop-darwin-#{arch}.dmg"
  name "Jolo"
  desc "Desktop app for working with coding agents"
  homepage "https://jolo.build"

  app "Jolo.app"

  zap trash: [
    "~/Library/Application Support/Jolo",
    "~/Library/Caches/jolo",
    "~/Library/Preferences/dev.jolo.desktop.plist",
    "~/Library/Saved Application State/dev.jolo.desktop.savedState",
  ]
end
