# Generated by scripts/update-homebrew-tap.js — edit the script, not this file.
cask "jolo" do
  version "0.2.5"

  arch arm: "arm64", intel: "x64"

  sha256 arm:   "84c8bf9d0c4694c22a3b81ab3aa2d1de884b6bc4ebe42099eed76c0a77199345",
         intel: "a40aabb04492646d17746c6578cc468e9647df055b8075806f267cad712d3a7f"

  url "https://github.com/jolo-build/jolo/releases/download/v#{version}/jolo-desktop-darwin-#{arch}.dmg"
  name "Jolo"
  desc "Desktop app for working with coding agents"
  homepage "https://jolo.build"

  app "Jolo.app"

  zap trash: [
    "~/Library/Application Support/Jolo",
    "~/Library/Caches/jolo",
    "~/Library/Preferences/dev.jolo.desktop.plist",
    "~/Library/Saved Application State/dev.jolo.desktop.savedState",
  ]
end
