# Generated by scripts/update-homebrew-tap.js — edit the script, not this file.
class JoloCli < Formula
  desc "Terminal CLI for working with coding agents"
  homepage "https://jolo.build"
  version "0.2.6"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/jolo-build/jolo/releases/download/v#{version}/jolo-cli-darwin-arm64.tar.gz"
      sha256 "588b6e628f14d4ddb6e936fc9f7d31cec571864edce5e887fb58a8eb746bc8ca"
    end
    on_intel do
      url "https://github.com/jolo-build/jolo/releases/download/v#{version}/jolo-cli-darwin-x64.tar.gz"
      sha256 "78b1595fe72f6f743dd4c67acc9b7160a6e77c7d387415b1c629189124dcc380"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/jolo-build/jolo/releases/download/v#{version}/jolo-cli-linux-arm64.tar.gz"
      sha256 "f40ca363fa45ea1b79fd797c361bc6d66da079834fe31125b9ba766f09671a1c"
    end
    on_intel do
      url "https://github.com/jolo-build/jolo/releases/download/v#{version}/jolo-cli-linux-x64.tar.gz"
      sha256 "cb316080507707f083f8798bd1f46fcf97d96a50ec1a6204b075e4eb9b1fc461"
    end
  end

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"bin/jolo"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/jolo --version")
  end
end
