# Generated by scripts/update-homebrew-tap.js — edit the script, not this file.
class JoloCli < Formula
  desc "Terminal CLI for working with coding agents"
  homepage "https://jolo.build"
  version "0.2.5"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/jolo-build/jolo/releases/download/v#{version}/jolo-cli-darwin-arm64.tar.gz"
      sha256 "e98c10dbf3b01f3ba41b4ea8387c08a94dc4db21371c4004f0e953ee60db67e8"
    end
    on_intel do
      url "https://github.com/jolo-build/jolo/releases/download/v#{version}/jolo-cli-darwin-x64.tar.gz"
      sha256 "4e737ba603825271e7e6758c41af37bbf05d31ebedbeb8ccc88b40dd2d50f1c9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/jolo-build/jolo/releases/download/v#{version}/jolo-cli-linux-arm64.tar.gz"
      sha256 "6e056010de9faf3f86051c5233c8bb43470f95f331b8ddc9456de42196db40b3"
    end
    on_intel do
      url "https://github.com/jolo-build/jolo/releases/download/v#{version}/jolo-cli-linux-x64.tar.gz"
      sha256 "6dcd71236de7658f090d9e6abb15c36e73d8888a305ac6f1f90ba195acd12281"
    end
  end

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"bin/jolo"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/jolo --version")
  end
end
